# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='provider',
            name='password',
            field=models.CharField(default='qwer1234', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
